### ISSUE TITLE
Dark Mode don't work

### ISSUE THREAD

**Issue by Rychillie** [arshad/gatsby-themes#1] opened 2019-11-20 00:55 UTC
I followed README's steps to install the theme and dark mode doesn't work.

Demo:
<img width="1440" alt="Screen Shot 2019-11-19 at 21 55 10" src="https://user-images.githubusercontent.com/14102456/69199618-45b71080-0b17-11ea-863b-f8e48cc714f7.png">

My test:
<img width="1440" alt="Screen Shot 2019-11-19 at 21 55 49" src="https://user-images.githubusercontent.com/14102456/69199642-5e272b00-0b17-11ea-91d9-513bab7ec383.png">

Dark Mode Test:
<img width="1440" alt="Screen Shot 2019-11-19 at 21 58 00" src="https://user-images.githubusercontent.com/14102456/69199744-b1997900-0b17-11ea-9a6b-7749dcf56fe0.png">

**Comment by arshad** [comment] 2019-11-20 05:33
@Rychillie do you see any error in your console? The way dark mode works is it adds a `mode-dark` class to `html` element and stores the value in `localStorage`.

**Comment by Rychillie** [comment] 2019-11-20 12:10
no errors in the terminal

![Screenshot_1](https://user-images.githubusercontent.com/14102456/69237902-7332a700-0b75-11ea-92da-a3b53565efe5.png)

![Screenshot_2](https://user-images.githubusercontent.com/14102456/69237924-7e85d280-0b75-11ea-9c8f-04846d95f3d3.png)

**Comment by Rychillie** [comment] 2019-11-20 14:08
@arshad i performed an "Audit" and returned this to me:

![Screenshot_3](https://user-images.githubusercontent.com/14102456/69245680-0a075f80-0b86-11ea-8d5a-c270468924b8.png)

**Comment by Rychillie** [comment] 2019-11-21 17:16
@arshad Any updates? I reinstalled several times, and the same thing always happens, even on different computers.

You could also write in the documentation how to install on github or Netlify.

**Comment by arshad** [comment] 2019-11-21 17:35
@Rychillie I think I figured it out. The `mode` is not properly set on initial load. I'll push a fix for it.

**Comment by arshad** [comment] 2019-11-21 18:00
@Rychillie I pushed a new version. Can you update and let me know if it works?

**Comment by duncanjbain** [comment] 2019-11-28 10:47
> @Rychillie I pushed a new version. Can you update and let me know if it works?

Hi Arshad, I’ve just published your theme yesterday [here](https://duncanbain.io/) and night theme isn’t working, I’ve not tried to troubleshoot it myself yet though.

**Comment by Rychillie** [comment] 2019-11-28 12:11
> > @Rychillie I pushed a new version. Can you update and let me know if it works?
> 
> Hi Arshad, I’ve just published your theme yesterday [here](https://duncanbain.io/) and night theme isn’t working, I’ve not tried to troubleshoot it myself yet though.

this is the same problem i have

**Comment by arshad** [comment] 2019-11-28 16:45
I've not been able to reproduce this locally but @duncanjbain thanks for the link, I'll take a look at this. This should make it easier to debug. I'll report back.

**Comment by arshad** [comment] 2019-11-28 16:53
OK I see. Seems like we're hitting this bug https://github.com/ChanceArthur/tailwindcss-dark-mode/issues/8. (See gif below)

![phoenix-tailwind-dark-mode](https://user-images.githubusercontent.com/124599/69822989-1e4ffa00-1221-11ea-9015-342a1efa6a26.gif)



I'll look into it.

**Comment by duncanjbain** [comment] 2019-11-28 21:42
> OK I see. Seems like we're hitting this bug [ChanceArthur/tailwindcss-dark-mode#8](https://github.com/ChanceArthur/tailwindcss-dark-mode/issues/8). (See gif below)
> 
> ![phoenix-tailwind-dark-mode](https://user-images.githubusercontent.com/124599/69822989-1e4ffa00-1221-11ea-9015-342a1efa6a26.gif)
> 
> I'll look into it.

Looks like the proposed fix is to use a previous version in the themes package.json that didn't seem to append the extra "/". I'm pretty new to Gatsby so I'm not sure how I can alter the dependencies of the theme to try it myself!

**Comment by miller-productions** [comment] 2019-12-29 06:26
Hi @arshad,

Great work with Phoenix. I've just started looking and it looks good.

I've just hit this bug also.

In the meantime, is there a way I can remove the use of this dark mode feature until this bug is fixed? i.e. comment it out somewhere?

**Comment by arshad** [comment] 2019-12-29 09:32
Hi @miller-productions I need to create a new release with this fix but I'm away for the holidays right now. 

As a temp fix you could [shadow](https://www.gatsbyjs.org/docs/themes/shadowing/) the [header](https://github.com/arshad/gatsby-themes/blob/master/themes/gatsby-theme-phoenix/src/components/header.js) component and remove the part that toggles the dark mode.

https://github.com/arshad/gatsby-themes/blob/534ba5ed37356fee9aa8800e37c83544125f6cd3/themes/gatsby-theme-phoenix/src/components/header.js#L61-L73

**Comment by miller-productions** [comment] 2019-12-30 03:43
Perfect @arshad, that will be fine for now (shadow the header).

Thanks for the point in the right direction, much appreciated.

Dan

**Comment by miller-productions** [comment] 2019-12-30 06:56
Done. Shadowing works.

To get it to work, I had to change the path for the import Icon line...

https://github.com/arshad/gatsby-themes/blob/ca4c170a8699476ee9b4d84da306a7a1d958cc6f/themes/gatsby-theme-phoenix/src/components/header.js#L4

to something that has a bit of a smell to it...

i.e. 

`import Icon from "../../../../node_modules/@arshad/gatsby-theme-phoenix/src/components/icon"
`

Question: what do you think about the way I did went about that?

**Comment by arshad** [comment] 2020-01-21 07:05
It looks like the latest `tailwindcss-dark-mode` has fixed this. I'm going to close this issue.

@miller-productions You can also do `import Icon from "@arshad/gatsby-theme/phoenix/src/components/icon"`

**Closed by arshad** 2020-01-21 07:05 UTC
Labels: bug, gatsby-theme-phoenix
